namespace DatasheetGenerator.Services;

using System.Text;
using DatasheetGenerator.Models;

public sealed class CodeGenerationService
{
  public string GenerateCode(string schemaName, IReadOnlyList<SchemaColumn> columns)
  {
    var className = $"{schemaName}GameData";
    var nestedTypes = new List<string>();
    var bodySb = new StringBuilder();
    AppendClassBody(bodySb, className, columns, nestedTypes);

    foreach (var nested in nestedTypes)
    {
      bodySb.AppendLine();
      bodySb.Append(nested);
    }

    var header = BuildHeader();
    return header + bodySb.ToString();
  }

  private static string BuildHeader()
  {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("namespace GameData;");
    sb.AppendLine();
    sb.AppendLine("using System;");
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine("using System.Collections.Frozen;");
    sb.AppendLine();
    return sb.ToString();
  }

  private static void AppendClassBody(StringBuilder sb, string className, IReadOnlyList<SchemaColumn> columns, List<string> nestedTypes)
  {
    sb.AppendLine($"public sealed record {className}");
    sb.AppendLine("{");

    foreach (var col in columns)
    {
      var attribute = GetTimespanAttribute(col);
      if (attribute is not null)
      {
        sb.AppendLine($"    {attribute}");
      }

      var typeName = GetCSharpType(col, className, nestedTypes);
      var defaultValue = GetDefaultValue(col, typeName);
      if (defaultValue is not null)
      {
        sb.AppendLine($"    public {typeName} {col.Name} {{ get; init; }} = {defaultValue};");
      }
      else
      {
        sb.AppendLine($"    public {typeName} {col.Name} {{ get; init; }}");
      }
    }

    sb.AppendLine("}");
  }

  private static string? GetTimespanAttribute(SchemaColumn col)
  {
    return col.Format switch
    {
      "timespan-hour" => "[TimeSpanType(TimeSpanType.Hour)]",
      "timespan-minute" => "[TimeSpanType(TimeSpanType.Minute)]",
      "timespan-second" => "[TimeSpanType(TimeSpanType.Second)]",
      "timespan-millisecond" => "[TimeSpanType(TimeSpanType.Millisecond)]",
      _ => null
    };
  }

  private const string SchemaRefSeparator = ".schema.json#/definitions/";

  private static string GetCSharpType(SchemaColumn col, string className, List<string> nestedTypes)
  {
    if (col.Ref is not null)
    {
      var sepIdx = col.Ref.IndexOf(SchemaRefSeparator, StringComparison.Ordinal);
      if (sepIdx > 0)
      {
        var schemaName = col.Ref[..sepIdx];
        var typeName = col.Ref[(sepIdx + SchemaRefSeparator.Length)..];
        if (schemaName.Equals("enum", StringComparison.OrdinalIgnoreCase) && !string.IsNullOrEmpty(typeName))
        {
          return col.IsNullable ? $"{typeName}?" : typeName;
        }
      }
    }

    var baseType = (col.JsonType, col.Format) switch
    {
      ("object", "vector2") => "Vector2",
      ("object", "vector3") => "Vector3",
      ("object", "timespan") => "TimeSpan",
      ("string", "datetime") => "DateTime",
      ("integer", var f) when f is "timespan-hour" or "timespan-minute" or "timespan-second" or "timespan-millisecond" => "TimeSpan",
      ("integer", _) => "int",
      ("number", _) => "float",
      ("boolean", _) => "bool",
      ("string", _) => "string",
      ("array", _) => GetArrayCSharpType(col, className, nestedTypes),
      _ => "object"
    };

    return col.IsNullable ? $"{baseType}?" : baseType;
  }

  private static string GetArrayCSharpType(SchemaColumn col, string className, List<string> nestedTypes)
  {
    var itemType = GetItemCSharpType(col, className, nestedTypes);
    return col.Format is "frozen-dictionary"
      ? $"FrozenDictionary<string, {itemType}>"
      : $"IReadOnlyList<{itemType}>";
  }

  private static string GetItemCSharpType(SchemaColumn col, string className, List<string> nestedTypes)
  {
    if (col.ItemChildren.Count > 0)
    {
      var nestedClassName = $"{className}{col.Name}Item";
      var nestedSb = new StringBuilder();
      AppendClassBody(nestedSb, nestedClassName, col.ItemChildren, nestedTypes);
      nestedTypes.Add(nestedSb.ToString());
      return nestedClassName;
    }

    return col.ItemJsonType switch
    {
      "integer" => "int",
      "number" => "float",
      "boolean" => "bool",
      _ => "string"
    };
  }

  private static string? GetDefaultValue(SchemaColumn col, string typeName)
  {
    if (col.IsNullable) { return null; }

    if (typeName == "string") { return "string.Empty"; }
    if (typeName.StartsWith("IReadOnlyList<", StringComparison.Ordinal)) { return "[]"; }
    if (typeName.StartsWith("FrozenDictionary<", StringComparison.Ordinal)) { return $"{typeName}.Empty"; }
    return null;
  }
}
